PID=0x1230
SPI_FILE = ../xilinx/UXN1230.spi
PY_CLASS = nitro_parts.BrooksEE.UXN1230

include ../lib/Makefiles/nitro_boards.mk

dram:
	ubitests UXN1230/ubitest/dram.py -M ubitest.testmanager.StressTester